version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: zump-postgres
    environment:
      POSTGRES_DB: zump
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zump-network

  # Redis Cache & Distributed Lock
  redis:
    image: redis:7-alpine
    container_name: zump-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - zump-network
    command: redis-server --appendonly yes

  # Zookeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zump-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - zump-network

  # Kafka Event Broker
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: zump-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - zump-network

  # Kafka UI (Optional - for monitoring)
  # kafka-ui:
  #   image: provectuslabs/kafka-ui:latest
  #   container_name: zump-kafka-ui
  #   depends_on:
  #     - kafka
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
  #   networks:
  #     - zump-network

  # Redis Commander (Optional - for Redis monitoring)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: zump-redis-commander
    depends_on:
      - redis
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    networks:
      - zump-network

volumes:
  postgres_data:
  redis_data:
  kafka_data:

networks:
  zump-network:
    driver: bridge
